### ISSUE TITLE
ossaudiodev.c:33:27: fatal error: sys/soundcard.h: No such file or directory

### ISSUE THREAD

**Issue by m-kuhn** [rave-engine/python3-android#4]
The file can be found in the NDK source tree in the include directory `linux/soundcard.h`. I guess the python sourcecode needs a patch to search for this file in the correct location.

**Comment by Shizmob** [comment]
It seems it builds fine with `sys/soundcard.h` linked to `linux/soundcard.h`, so I fixed that. Thanks for the suggestion!
