### ISSUE TITLE
Fatal Python error: Py_Initialize: can't initialize sys

### ISSUE THREAD

**Issue by ljgabc** [rave-engine/python3-android#7]
Hi, I build Python-3.4.2 follow the build.sh, but run failed.

python	python3.4.2
android	4.4.3

\# export PYTHONHOME=/data/Python-3.4.2
\# /data/Python-3.4.2/bin/python3
Fatal Python error: Py_Initialize: can't initialize sys
sys.excepthook is missing
object  : ValueError('character U+7461642f is not in range [U+0000; U+10ffff]',)
type    : ValueError
refcount: 1
address : 0x76cf7660
lost sys.stderr
[1] + Stopped (signal)     python

**Comment by Shizmob** [comment]
Hi!

It seems like it’s encountering some invalid bytestream very early on in the `sys` module initialisation, possibly related to an invalid filesystem path.
Judging from [this code](https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1654 <https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1654>) it could be a lot of things, but I suspect it’s one of the statements that start [from here](https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1727 <https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1727>) that causes the error.

Could I possibly get the output of running `env` in your shell, and would it be possible for you to hook up `gdb` to it and get a backtrace of the crash?
Alternatively, running `arm-none-eabi-addr2line -e build/*/bin/python3 0x76cf7660` could also help a lot to help me figure out where exactly the crash occurred.

Thanks!
- Shiz

**Comment by Shizmob** [comment]
Hi!

It seems like it’s encountering some invalid bytestream very early on in the `sys` module initialisation, possibly related to an invalid filesystem path.
Judging from [this code](https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1654) it could be a lot of things, but I suspect it’s one of the statements that start [from here](https://github.com/python/cpython/blob/143dddd6e2347ff3d5cfd278361f508a1ae6d0b1/Python/sysmodule.c#L1727) that causes the error.

Could I possibly get the output of running `env` in your shell, and would it be possible for you to hook up `gdb` to it and get a backtrace of the crash?
Alternatively, running `arm-none-eabi-addr2line -e build/*/bin/python3 0x76cf7660` on the build computer could also help a lot to help me figure out where exactly the crash occurred.

Thanks!
- Shiz

**Comment by ljgabc** [comment]
Hi, 
    I recompiled the source and now it runs successfully on my board, so I cannot get the detail information again. Maybe it's my own mistake. Sorry for this, I'll close this issue.

**Comment by Purgox** [comment]
Glad it worked out, don't be afraid to re-open if it pops up again. :)

**Comment by Shizmob** [comment]
Glad it worked out, don't be afraid to re-open if the issue pops up again. :)

**Comment by michalliu** [comment]
```
1705     SET_SYS_FROM_STRING("executable",
1706                         PyUnicode_FromWideChar(
1707                                Py_GetProgramFullPath(), -1));
1708     SET_SYS_FROM_STRING("prefix",
1709                         PyUnicode_FromWideChar(Py_GetPrefix(), -1));
1710     SET_SYS_FROM_STRING("exec_prefix",
1711                         PyUnicode_FromWideChar(Py_GetExecPrefix(), -1));
1712     SET_SYS_FROM_STRING("base_prefix",
1713                         PyUnicode_FromWideChar(Py_GetPrefix(), -1));
```
It crashed at 1708

**Comment by Shizmob** [comment]
Does this also occur with @yan12125's [fork](https://github.com/yan12125/python3-android)? I haven't looked into this for a while, honestly.
